name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy when main is updated

permissions:
  contents: write  # ✅ Ensures GitHub Actions can push to gh-pages branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # ✅ Avoids GitHub token conflicts

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20  

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Ensure CNAME file is included
        run: cp CNAME dist/  # ✅ Ensures CNAME is deployed

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          clean: true  # ✅ Removes old files
          single-commit: true  # ✅ Keeps history clean
          token: ${{ secrets.GITHUB_TOKEN }}  # ✅ Uses GitHub token for authentication
          cname: hugoveuillet.com
